Add group message listview and business-logic for it
Snare295/VirtMNC-client pull request #3
Opened 2023-06-07 21:03 UTC by Snare295

2023-06-07 21:24 UTC, bLuDd1 requested changes

2023-06-07 21:24 UTC, bLuDd1 commented on lib/ui/widgets/message/group/group_message_tile.dart
> +  bool isMe;
Move this properties to the top of the class declaration.

2023-06-07 21:24 UTC, bLuDd1 commented on lib/ui/widgets/message/group/group_message_tile.dart
> +        print(UserData().name);
Delete unnecessary prints

2023-06-07 21:24 UTC, bLuDd1 commented on lib/ui/widgets/message/group/group_message_tile.dart
> +    if (isMe == true) {
Simplify if statement to 
```suggestion
    if (isMe) {
```

2023-06-08 12:21 UTC, Snare295 commented on lib/ui/widgets/message/group/group_message_tile.dart
> +        print(UserData().name);
Deleted

2023-06-08 12:21 UTC, Snare295 commented on lib/ui/widgets/message/group/group_message_tile.dart
> +    if (isMe == true) {
Ok

2023-06-08 12:22 UTC, Snare295 commented on lib/ui/widgets/message/group/group_message_tile.dart
> +  bool isMe;
Moved, but constructor still will be before builder method

2023-06-08 12:22 UTC, merged